Class {
	#name : #GtMagritteMementoValueChangedAnnouncement,
	#superclass : #GtMagritteMementoAnnouncement,
	#instVars : [
		'description',
		'result'
	],
	#category : #'GToolkit-Magritte-Announcements'
}

{ #category : #accessing }
GtMagritteMementoValueChangedAnnouncement >> description [

	^ description
]

{ #category : #accessing }
GtMagritteMementoValueChangedAnnouncement >> description: anObject [

	description := anObject
]

{ #category : #accessing }
GtMagritteMementoValueChangedAnnouncement >> result [

	^ result
]

{ #category : #accessing }
GtMagritteMementoValueChangedAnnouncement >> result: anObject [

	result := anObject
]
