Class {
	#name : #GtMagritteMementoValueCommittedAnnouncement,
	#superclass : #GtMagritteMementoAnnouncement,
	#instVars : [
		'description',
		'result'
	],
	#category : #'GToolkit-Magritte-SecondImplementation-Announcements'
}

{ #category : #accessing }
GtMagritteMementoValueCommittedAnnouncement >> description [

	^ description
]

{ #category : #accessing }
GtMagritteMementoValueCommittedAnnouncement >> description: anObject [

	description := anObject
]

{ #category : #accessing }
GtMagritteMementoValueCommittedAnnouncement >> result [

	^ result
]

{ #category : #accessing }
GtMagritteMementoValueCommittedAnnouncement >> result: anObject [

	result := anObject
]
