Class {
	#name : #GtMagritteMementoValidationChangedAnnouncement,
	#superclass : #GtMagritteMementoAnnouncement,
	#instVars : [
		'result'
	],
	#category : #'GToolkit-Magritte-SecondImplementation-Announcements'
}

{ #category : #accessing }
GtMagritteMementoValidationChangedAnnouncement >> result [

	^ result
]

{ #category : #accessing }
GtMagritteMementoValidationChangedAnnouncement >> result: anObject [

	result := anObject
]
