Class {
	#name : #GtMagritteMementoCreationFailure,
	#superclass : #GtMagritteResult,
	#instVars : [
		'object',
		'description'
	],
	#category : #'GToolkit-Magritte-SecondImplementation-Models'
}

{ #category : #accessing }
GtMagritteMementoCreationFailure >> description [

	^ description
]

{ #category : #accessing }
GtMagritteMementoCreationFailure >> description: anObject [

	description := anObject
]

{ #category : #accessing }
GtMagritteMementoCreationFailure >> object [

	^ object
]

{ #category : #accessing }
GtMagritteMementoCreationFailure >> object: anObject [

	object := anObject
]
