Class {
	#name : #GtMagritteMementoCommittedAnnouncement,
	#superclass : #GtMagritteMementoAnnouncement,
	#instVars : [
		'result'
	],
	#category : #'GToolkit-Magritte-SecondImplementation-Announcements'
}

{ #category : #accessing }
GtMagritteMementoCommittedAnnouncement >> result [

	^ result
]

{ #category : #accessing }
GtMagritteMementoCommittedAnnouncement >> result: anObject [

	result := anObject
]
