Class {
	#name : #GtMagritteDummyBePrimaryPostalAddressRequest,
	#superclass : #Announcement,
	#instVars : [
		'address',
		'response'
	],
	#category : #'GToolkit4Magritte-Examples-Support'
}

{ #category : #accessing }
GtMagritteDummyBePrimaryPostalAddressRequest >> address [

	^ address
]

{ #category : #accessing }
GtMagritteDummyBePrimaryPostalAddressRequest >> address: anObject [

	address := anObject
]

{ #category : #accessing }
GtMagritteDummyBePrimaryPostalAddressRequest >> response [

	^ response
]

{ #category : #accessing }
GtMagritteDummyBePrimaryPostalAddressRequest >> response: anObject [

	response := anObject
]
