Class {
	#name : #GtMagritteDummyPostalAddressIsPrimaryChanged,
	#superclass : #Announcement,
	#instVars : [
		'address',
		'isPrimary'
	],
	#category : #'GToolkit4Magritte-Examples-Support'
}

{ #category : #accessing }
GtMagritteDummyPostalAddressIsPrimaryChanged >> address [

	^ address
]

{ #category : #accessing }
GtMagritteDummyPostalAddressIsPrimaryChanged >> address: anObject [

	address := anObject
]

{ #category : #accessing }
GtMagritteDummyPostalAddressIsPrimaryChanged >> isPrimary [

	^ isPrimary
]

{ #category : #accessing }
GtMagritteDummyPostalAddressIsPrimaryChanged >> isPrimary: anObject [

	isPrimary := anObject
]
