Class {
	#name : #GtMagritteDummyPostalAddressStreetChanged,
	#superclass : #Announcement,
	#instVars : [
		'address',
		'street'
	],
	#category : #'GToolkit4Magritte-Examples-Support'
}

{ #category : #accessing }
GtMagritteDummyPostalAddressStreetChanged >> address [

	^ address
]

{ #category : #accessing }
GtMagritteDummyPostalAddressStreetChanged >> address: anObject [

	address := anObject
]

{ #category : #accessing }
GtMagritteDummyPostalAddressStreetChanged >> street [

	^ street
]

{ #category : #accessing }
GtMagritteDummyPostalAddressStreetChanged >> street: anObject [

	street := anObject
]
